[package]
name = "aurorix-storage"
description = "Aurorix local persistence adapters."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aurorix-model = { path = "../aurorix-model" }
rusqlite.workspace = true
sha2.workspace = true
uuid.workspace = true

[lints]
workspace = true
